#!/bin/bash

script_name=$1
description=$2

if [ "$3" ]
then
   pe_batch=$3
else
   pe_batch="1"
fi

if [ "$4" ]
then
   do_dbstop=$3
else
   do_dbstop="0"
fi
mlcmd="run_script('$script_name', '$description', 1);"

#############################################
# Can't effectively debug when in qsub mode #
#############################################
#if [ "$do_dbstop" == "1" ]
#then
#   mlcmd="dbstop if error; $mlcmd"
#fi
#echo $mlcmd

#qsub_cmd="qsub -pe batch $pe_batch 'cd /groups/saalfeld/home/bogovicj/dev/main/hhmi-exp; /misc/local/matlab-2013b/bin/matlab -nodesktop -nosplash -r '$mlcmd''"
#echo $qsub_cmd

echo "cd /groups/saalfeld/home/bogovicj/dev/main/hhmi-exp; /misc/local/matlab-2013b/bin/matlab -nodesktop -nosplash -r \"$mlcmd\"" | qsub -pe batch $pe_batch -N $script_name -l matlab=1

#echo "cd /groups/saalfeld/home/bogovicj/dev/main/hhmi-exp; /misc/local/matlab-2013b/bin/matlab -nodesktop -nosplash -r \"$mlcmd\"" | qsub -pe batch -o ~/clusterJobs/ $pe_batch -N $script_name
